config/routes.rb
Rails.application.routes.draw do

  get 'game', to: 'longest#game'

  get 'score', to: 'longest#score'

  root to: 'longest#home'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/longest_controller.rb
class LongestController < ApplicationController
  def game
    longest_word = LongestWord.new
    @grid = longest_word.generate_grid(9)
    @start_time = Time.now
  end

  def score
    @attempt = params[:attempt]
    @grid = JSON.parse(params[:grid])
    @start_time = Time.parse(params[:start_time])
    longest_word = LongestWord.new
    @end_time = Time.now
    @result = longest_word.run_game(@attempt, @grid, @start_time, @end_time)
  end

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all         # GET /restaurants
  end

  def show
  end

  def new
    @user = User.new
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    @user.save

    redirect_to users_path
  end

  def edit
  end

  def update        # PATCH /restaurants/:id
    @user.update(user_params)

    redirect_to users_path
  end

  def destroy
    @user.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/longest_helper.rb
module LongestHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/longest/game.html.erb
<div class="container-fluid">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3 text-center">
        <%= @session %>
        <h2>Welcome to the longest word-game!</h2>
        <h3>Here is your grid:</h3>
        <ul class="list-inline">
          <% @grid.each do |z| %>
            <li><%= z %></li>
          <% end %>
        </ul>

        <form action="/score" method="get" class="form-inline">
          <div class="form-group">
            <label for="attempt">Your attempt</label>
            <input type="text" name="attempt" id="attempt" class="form-control">
            <input type="hidden" name="grid" value="<%= @grid %>">
            <input type="hidden" name="start_time" value="<%= @start_time %>">
          </div>
          <input type="submit" value="Send" class="btn btn-primary">
        </form>
      </div>
    </div>
  </div>
</div>

app/views/longest/home.html.erb
<div class="container-fluid">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3 text-center">
        <h1>Welcome to the Longest-word game! :) </h1>
        <%= link_to " + Click here to start a new game!", game_path %>
      </div>
    </div>
  </div>
</div>

app/views/longest/score.html.erb
<div class="container-fluid">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3 text-center">
        <p>Your attempt: <%= @attempt %></p>
        <p>The grid: <%= @grid %></p>
        <p><% @x = @start_time %></p>
        <p><%= ((@end_time - @x) / 60).floor %> minutes, <%= (@end_time - @x).round(1)  %> segundos</p>
        <p>Translation: <%= @result[:translation] %></p>
        <p>Score: <%= @result[:score].to_i %></p>
        <p>Result: <%= @result[:message] %></p>

        <%= link_to "+ New attempt", game_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/users/create.html.erb
<%= render 'form' %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<div class="container-fluid">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3 text-center">
        <% @users.each do |user| %>
          <ul>
            <li><%= link_to user.name, user_path(user) %> ~> <%= user.points %> points</li>
              <ul>
                <li><%= link_to "Delete", user_path(user), method: :delete, data: { confirm: "Are you sure?" } %></li>
                <li><%= link_to "Edit user", edit_user_path(user) %></li>
              </ul>
          </ul>
        <% end %>
        <%= link_to " + Click here to start a new game!", game_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container-fluid">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3 text-center">
        <h1>Plays as:</h1>
        <% @users.each do |user| %>
        <ul>
          <li><%= link_to user.name, user_path(user) %></li>
        <% end  %>
        </ul>
      </div>
    </div>
    <div class="row text-center">
      <h4>Create a new user:</h4>
      <div class="col-sm-6 col-sm-offset-3">
        <%= render 'form' %>
      </div>
    </div>
    <div class="row text-center">
      <div class="col-sm-6 col-sm-offset-3">
        <h4><%= link_to "Start a new game", game_path %></h4>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3 text-center">
        <h1><%= @user.name %></h1>
        <h4><%= @user.points %> points</h4>
      </div>
    </div>
  </div>
</div>